### ISSUE TITLE
Bug in new version 0.0.10

### ISSUE THREAD

**Issue by vore** [Haxiboy/node-red-contrib-looptimer-advanced#9]
Hello!
Looks like there is a bug since the update to 0.0.10.
As soon as I inject any paylaod the debug tab will output "TypeError: msg.payload.toLowerCase is not a function".

Could you please check for this?

Thank you!

**Comment by Haxiboy** [comment]
Fixed in new version 0.0.11 and up!
